[target.thumbv7em-none-eabihf] 
runner = "probe-rs run --connect-under-reset --chip STM32G431KB" 
rustflags = [
  "-C", "link-arg=-Tlink.x", 
  "-C", "link-arg=-Tdefmt.x"
]

[build] 
target = "thumbv7em-none-eabihf" 
